### ISSUE TITLE
fix gh action

### ISSUE THREAD

**Issue by EkChills** [EkChills/prac-actions#1]
``` yaml
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          echo "building..."
          npm run build
          echo "build completed"
```
